# Generated by Django 4.2.4 on 2025-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="price_range_max",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="price_range_min",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_category",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="title",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
