# Generated by Django 4.2.4 on 2025-04-30 07:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart_manager", "0002_remove_cartitem_price_range_max_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CartItem",
            new_name="Cart",
        ),
    ]
