# Generated by Django 4.2.4 on 2025-04-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_manager", "0003_rename_cartitem_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="report_data",
            field=models.TextField(),
        ),
    ]
