version: '3.9'

services:
  web:
    build: .
    container_name: 'ecommerce_backend'
    command: uvicorn ecommerce_backend.asgi:application --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
      - sqlite_data:/app/db
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=ecommerce_backend.settings
      - DEBUG=1
volumes:
  sqlite_data:
