# Generated by Django 4.2.20 on 2025-06-08 07:17

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=250)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (".pdf", "PDF"),
                            (".jpg", "JPG"),
                            (".jpeg", "JPEG"),
                            (".docx", "DOCX"),
                            (".png", "PNG"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("size", models.PositiveBigIntegerField(help_text="size in bytes")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
