# Generated by Django 4.2.4 on 2025-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill_manager", "0002_alter_bill_managers_alter_bill_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
