# Generated by Django 4.2.4 on 2026-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_manager', '0003_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.CharField(blank=True, choices=[('groceries', 'GROCERIES'), ('dining', 'DINING'), ('utilities', 'UTILITIES'), ('transport', 'TRANSPORT'), ('healthcare', 'HEALTHCARE'), ('entertainment', 'ENTERTAINMENT'), ('shopping', 'SHOPPING'), ('travel', 'TRAVEL'), ('education', 'EDUCATION'), ('services', 'SERVICES'), ('other', 'OTHER')], db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bill',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
